  
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: {{ .Values.containerPort }}
    {{ if eq .Values.service.type "NodePort" -}}
    nodePort: 30383 
    {{ end -}}
  type: {{ .Values.service.type }}